### PR TITLE
Update Add-On Notice Types Info

### PR DESCRIPTION
**Pull request by Noordfrees**
This repo's side of https://github.com/widelands/widelands-website/pull/374

This should be tested carefully on alpha before merging, however alpha is currently running #127

Btw I already created the noticetypes on the website, however the settings there are ignored until this PR is merged.

### CODE REVIEW

**Comment by Noordfrees** [comment]
This is up on alpha now. I changed the noticetype slugs on alpha to what this branch expects.

**Comment by frankystone** [comment]
Do edited comments send again?

**Comment by Noordfrees** [comment]
Only to users who are @mentioned in the edited version but not in the original. Otherwise it would be e-mail spamming IMHO since it's not uncommon to edit a comment multiple times. I tried to keep this consistent with forum and GitHub notifications.

**Comment by frankystone** [comment]
Wrote some comments with mentioning you to 'auto_soldiers_cs.wad'. Do you get emails?

**Comment by frankystone** [comment]
Hm, wrong spelling of your name i think.

**Comment by frankystone** [comment]
Looks like everything is working fine :+1: 

It would be nice to have a popup of usernames if one writes `@+Letter`... to prevent misspelling ;)
New comments are only shown if one leaves the 'Add-Ons'-section and click on Add-Ons in the main menu again. But i think this can be ignored.

**Comment by Noordfrees** [comment]
> It would be nice to have a popup of usernames if one writes @+Letter... to prevent misspelling ;)

+1 but for this to work the server would need to send the complete list of all registered usernames to the client once. Communicating after every keystroke instead would be very slow. Do we want this?

> New comments are only shown if one leaves the 'Add-Ons'-section and click on Add-Ons in the main menu again. But i think this can be ignored.

Alternatively you can click the *Refresh Remotes* button to update the add-ons info

**Comment by frankystone** [comment]
> > It would be nice to have a popup of usernames if one writes @+Letter... to prevent misspelling ;)
> 
> +1 but for this to work the server would need to send the complete list of all registered usernames to the client once. Communicating after every keystroke instead would be very slow. Do we want this?

We have similar functionality on the website which calls a function to query the users database if at least 3 Characters are written. This reduces the amount of available usernames. But i don't know if this is feasable for the addons server because the ajax connection on the website is provided by jquery.
See: https://github.com/widelands/widelands-website/blob/master/django_messages_wl/views.py
and: https://github.com/widelands/widelands-website/blob/dd9f35559a7726d9f597237662c0df064bec6b9b/templates/django_messages/compose.html#L10-L16

**Comment by frankystone** [comment]
This has been heavily tested on alpha and should be good to go.

Anyway i am a bit concerned about the hardcoded values. This means every time a notice type's slug changes the code has to be adopted. This is also difficult if there are other slugs on alpha than on the productive system. Can't there be an other config file which defines the mappings of slug <-> notice type? So there can be other slugs for alpha than in productive.

**Comment by Noordfrees** [comment]
Thanks for the review :)
Merged and deployed.

**Pull request merged**
