### PR TITLE
String fixes for first heroes win

### LINKED ISSUE #35: First Heroes Win string issues
@frankystone 3 transifex string issues were found in the First Heroes Win resource:

- `The player who has at least %1% fully trained soldiers in his warehouses wins the game.`
    -  The statement is confusing. Why is "at least" there? Could the winner have also more heroes? And why isn't "as first one" there? Everyone who will have more than the number of heroes wins? I really don't understand its confusing. The sentence says something, I don't expect. 
- `%1% heroes`
    -  When compound messages are used it is good to leave a developer comment on how the sentence is build. It is not clear what case should I use here 1st or 4th, it makes a difference.
https://en.wikipedia.org/wiki/Czech_declension 
- `%1%: %2%`
    -  Developer note needed.

### PR DESCRIPTION
**Pull request by frankystone**
fixes #35

### CODE REVIEW

**Comment by Noordfrees** [comment]
LGTM
This needs a version increase to 1.0.1 now

**Comment by Noordfrees** [comment]
Whoops, my changes to master earlier introduced a splendid merge conflict. I'll merge this from the commandline now.

**Comment by frankystone** [comment]
Damn 1: Yetserday i thought abot increasing the version, this morning not.

Damn 2: Should i remove the metadata/first_heroes_win.wad and ran updatelist again?

**Comment by frankystone** [comment]
thanks.

**Comment by Noordfrees** [comment]
Merged in 9a846a7

**Pull request closed without merging**
