### PR TITLE
Set Server Socket Receive Buffer Size

### PR DESCRIPTION
**Pull request by Noordfrees**
This seems to fix https://github.com/widelands/widelands/issues/5117 after testing briefly on the alpha server

This feels like a workaround, not sure if there may be a better way?

### CODE REVIEW

**Comment by frankystone** [comment]
Got the checksum mismatch locally when trying to upload minimalistic_theme.wad locally.

Then i added the change from https://github.com/widelands/wl_addons_server/pull/109/commits/58be42c0ce0896cb8936a32c18e0bc815d9651c0 but this does not solve the problem.

~~~~
[00:02:26.001 real] ERROR: upload addon minimalistic_theme.wad: Connection interrupted (Broken pipe). Reason: 
[00:02:26.001 real] ERROR: WL Protocol Exception: Checksum mismatch for /tmp/4658040621826592119/loadscreens/gameloading/summer/haselstein.png: expected 60dde83451f014a0f164c458cd0b3111, found c8e62f4b916a3f3fb3935127b09cb01f
~~~~
Most worth: widelands hangs endlessly and i have to kill the process.

Uploading `no_default_resources.wad` works but the files aren't stored below the folder `~/wl-addon-server/wl_addons_server/addons`, but this is another issue i guess.

Since i can trigger the issue locally: Anything i can do to help?

**Comment by Noordfrees** [comment]
:(

Another cause might be that Widelands sends the data faster than the network can handle it so the *send* buffer gets corrupted. Can you try adding these lines to `src/network/net_addons.cc`
```diff
@@ At the top of the file @@
+ #include <SDL_timer.h>

@@ In function NetAddons::upload_addon, L757 @@
		for (const std::string& file : pair.second) {
+			SDL_Delay(100);
			std::string full_path = kAddOnDir;
```
and see whether the issue can still happen after recompiling?
(This change makes uploading much slower to give the network more time to handle the load)

**Comment by frankystone** [comment]
Hm. I have to apologize... I never thought it takes so long to send files via network to the same machine. Because the mouse doesn't react and i was impatient i killed the widelands process and i think because of that i got the checksum mismatch. Sorry...

Adding the SDL_Delay(100) makes me feel it didn't get slow, in contrary i feel it was faster. But measuring the time by hand gives me:
* without SDL_Delay: 4:40 min
* with SDL_Delay: 4:34 min

So the upload time can be considered equal i think. Adding SDL_Delay and `serverSocket.setReceiveBufferSize(Integer.MAX_VALUE);` the time needed for upload is 4:51 min.

Can you reproduce the checksum mismatch error?

**Comment by Noordfrees** [comment]
Superseded by https://github.com/widelands/widelands/pull/5231

**Pull request closed without merging**
