### PR TITLE
new add-on: auto_soldiers_cs

### PR DESCRIPTION
**Pull request by frankystone**
Finally here is my new addon.

Hopefully i did all things correctly for this merge request.

### CODE REVIEW

**Review by Noordfrees — COMMENTED** [review]
Two typos in the description: miliary → military and buildiung → building

The descname is a bit long, perhaps consider shortening it? e.g. "Autoconfigure Military Sites"

There was a change to the way the Java programs handle add-on metadata earlier today. The scripts should have created a new file `metadata/auto_soldiers_cs.wad` which is not contained in this branch yet. This file stores among other info the uploader name. (The java programs now fetch all such info from there; manual changes to the lists are overwritten on every run.) So please do
```
javac *.java
java UpdateList
# now edit metadata/auto_soldiers_cs.wad manually to change the uploader
java UpdateList   # again, so the change gets applied
git add .
git commit -m "Update metadata"
git push <target>
```

**Comment by frankystone** [comment]
Thanks for the explanations :-)

Done.

**Comment by Noordfrees** [comment]
You forgot to re-run `java UpdateList` after editing the metadata ;)

I'm next going to modify the program to prompt for the uploader name interactively instead of using a default value, for convenience.

**Comment by frankystone** [comment]
Thanks!

**Pull request merged**
